version: '3'
services:
  terraform-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform-container
    tty: true
    volumes:
      - .:/root
    environment:
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    env_file:
      - .env
